# Generated by Django 3.2.13 on 2022-06-13 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('even', 'Even'), ('avoid_one', 'Avoid one'), ('all_together', 'All together')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 23, 23, 15, 132248, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Event title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='EventRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number_of_seats', models.SmallIntegerField()),
                ('ticket_price', models.IntegerField()),
                ('related_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rows', to='event.event')),
            ],
        ),
    ]
