# Generated by Django 3.2.13 on 2022-06-17 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('even', 'Even'), ('avoid_one', 'Avoid one'), ('all_together', 'All together')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 4, 31, 45, 289649, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Event title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
